### PR TITLE
Search, Redux

### PR DESCRIPTION
**Pull request by quartzjer**
My weekend project went well, all in all well less than 10 hours, and we have a new search!

Clucene is gone, sqlite's fts is in, and it's wicked fast as well, very extensible, and we have a snippet feature now! (highlighted preview of the matching text). 2x as much code deleted as added and much less pain for new devs setting up a local env :)

All of the collections including links are now handled uniformly, and the update process is much much much more efficient using a new json streaming option.

There's two things left to do before pulling, a small visual bug in the UI (some are dup'd) I need help with, and the migration (just need to add it).  It's ready for some testing though, npm install then hit /update and run it through it's paces!

### CODE REVIEW

**Comment by quartzjer** [comment]
Oh, and I also have to update devdocs w/ the new features :)

**Comment by mdz** [comment]
Working OK for me so far, except for the known issue with the duplicates

**Comment by othiym23** [comment]
What's the rationale for moving from common/node/lsearch.js -> Collections/Search? Search is a verb and the rest of the collections represent aggregates of nouns. It feels very strange to me to have it factored that way.

**Comment by mdz** [comment]
It feels strange to me that Collections/Search exists at all!

**Comment by quartzjer** [comment]
The idea that additional collections would also serve as composite resources/tools has always been a goal, this is just the first opportunity to do it :)

It's also much cleaner, logic is all in one place.

**Comment by mdz** [comment]
The fact that you intended it all along doesn't make it less confusing for the rest of us. :-)

**Comment by othiym23** [comment]
I still don't understand how a "composite resource/tool" is a Collection, though. It seems like we have libraries connected to the core with behavior defined, and collections are where we deal with the first-class subjects of the locker. 

I'm not sure how I feel about the idea of it being cleaner to have the logic all in one place, either. Having the specific logic for specific services (independent of the synclets) all concentrated in the bits of domain-specific code has always felt strange to me, and this just feels even weirder. I know that Java developers love abstraction above all things, but keeping the specific data-type adaptors loosely coupled against the core logic of something like search seems like a much easier thing to understand and maintain in the long run.

**Comment by quartzjer** [comment]
Is this a terminology thing? I've been thinking about everything as a "service" and services and serve each other as much as they can apps.  It's a separation of logic and stack space, both of which are very well suited for how search is being used.

I don't see there being any libraries connected to core, core is a namespace and tools closely related to the namespace tasks, data functionality exists in the services.

**Comment by othiym23** [comment]
If you're thinking of everything as services, why are a certain number of them called Collections? "Collection" is a word with a specific meaning (for me), and it makes total sense to consider Places, Contacts, Photos and Links as collections, but search is something different -- a second-order byproduct of the data types, and a cross-cutting activity. To me that's a pretty major distinction. In that world, even though it's not a part of core (and I agree that my wording was imprecise there, sorry), it totally makes sense to have a library of search functionality in common/node/lsearch.js and a set of lightweight adapters that describe how to index and query the individual data types / external service types.

**Comment by mdz** [comment]
Forrest said everything I was going to say. Search makes sense to me as a "service" but not as a "collection"

**Comment by quartzjer** [comment]
There's been more than a few sporadic conversations about renaming /everything/ to "service" since the beginning almost, place service, search service, facebook service, etc, to help avoid these kinds of different interpretations.  I'm game :)

Aside from that, this search collection most definitely collects data as much as any other collection does, it just collects textual data, you could call it a text collection that has a query really, but that's even more confusing.

I like to think of collections (/services) as fully isolate-able, so having something like search be a shared library feels very troublesome, and difficult to maintain even when embedded in many places.  Having it speak the same language to other collections as a peer is easy to maintain, and even fully isolate and separate/replace if needed :)

**Comment by othiym23** [comment]
I think that to flatten everything out to "services" is a step backwards – there's a value to distinguishing the first-class entities the system is designed to manipulate from the second-order data derived from those entities, especially when the derived data is something that cuts across the rest of the data types. Search results are different from contacts or checkins.

If anything, having a library that handles the core search and indexing logic that stands apart from the entities being indexed is _more_ isolated than treating search as yet another service -- the adapters take in external documents and produce abstracted documents that are indexed, which acts as an abstraction barrier that hides the guts of search from the rest of the locker.

**Comment by quartzjer** [comment]
I think I see the specific thing you're saying, the transformation/mapping part that is in index.js, and I would mostly agree /except/ I prefer to generalize/librarieize only after it's painful not to. I really like to implement it where it's needed first, even when I know it will likely need to be generalized, that's pretty easy to do and you'll _always_ know more when you encounter the 2nd and 3rd needs.

**Comment by mdz** [comment]
Thinking about search as a collection of data _almost_ makes it make sense
to me.  I don't think of it as all the same type, though: that data has
structure.  Maybe we flatten it all at the moment, but logically, search is
an operation on objects, not only text, right?

On Mon, Dec 05, 2011 at 02:45:42PM -0800, Jeremie Miller wrote:

> There's been more than a few sporadic conversations about renaming /everything/ to "service" since the beginning almost, place service, search service, facebook service, etc, to help avoid these kinds of different interpretations.  I'm game :)
> 
> Aside from that, this search collection most definitely collects data as much as any other collection does, it just collects textual data, you could call it a text collection that has a query really, but that's even more confusing.
> 
> I like to think of collections (/services) as fully isolate-able, so having something like search be a shared library feels very troublesome, and difficult to maintain even when embedded in many places.  Having it speak the same language to other collections as a peer is easy to maintain, and even fully isolate and separate/replace if needed :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/pull/486#issuecomment-3024795

## 
- mdz

**Comment by quartzjer** [comment]
As implemented it's definitely the flattened sort, IMO the work that temas is doing on storage could impact the object style search so this isn't going too far in that direction yet. 

That said, it easily could still, and I want to explore some other ideas around "hooks" in the near future as a possible model to make this pattern friendly.

**Comment by mdz** [comment]
If I squint and think of it as the "searchables" collection, it works for
me.  I expect that when we have something else like it, which doesn't quite
fit with the other collections, we'll end up calling it something new.

On Mon, Dec 05, 2011 at 06:01:45PM -0800, Jeremie Miller wrote:

> As implemented it's definitely the flattened sort, IMO the work that temas is doing on storage could impact the object style search so this isn't going too far in that direction yet. 
> 
> That said, it easily could still, and I want to explore some other ideas around "hooks" in the near future as a possible model to make this pattern friendly.
> 
> On Dec 5, 2011, at 7:22 PM, Matt Zimmermanreply@reply.github.com wrote:
> 
> > Thinking about search as a collection of data _almost_ makes it make sense
> > to me.  I don't think of it as all the same type, though: that data has
> > structure.  Maybe we flatten it all at the moment, but logically, search is
> > an operation on objects, not only text, right?
> > 
> > On Mon, Dec 05, 2011 at 02:45:42PM -0800, Jeremie Miller wrote:
> > 
> > > There's been more than a few sporadic conversations about renaming /everything/ to "service" since the beginning almost, place service, search service, facebook service, etc, to help avoid these kinds of different interpretations.  I'm game :)
> > > 
> > > Aside from that, this search collection most definitely collects data as much as any other collection does, it just collects textual data, you could call it a text collection that has a query really, but that's even more confusing.
> > > 
> > > I like to think of collections (/services) as fully isolate-able, so having something like search be a shared library feels very troublesome, and difficult to maintain even when embedded in many places.  Having it speak the same language to other collections as a peer is easy to maintain, and even fully isolate and separate/replace if needed :)
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/LockerProject/Locker/pull/486#issuecomment-3024795
> > 
> > ## 
> > - mdz
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/LockerProject/Locker/pull/486#issuecomment-3026698
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/pull/486#issuecomment-3027082

## 
- mdz

**Comment by othiym23** [comment]
I think my point is that you have to distort the model of a "service" pretty heavily to make the data-type collections / endpoints and the search service / endpoint look like the same thing -- that's a level of abstraction that doesn't provide a whole lot of leverage for me.

I feel like we, collectively, have a pretty good feeling for how search ought to work, given that I think every single member of the team has implemented at least one search service in the past, and as such we don't need to be too too experimental about how we implement our search service. The access patterns around storage and representation and the usage patterns around search are different, both conceptually and concretely, than the other data types we work with. I can see search broadening (to deal with things like location data), and I do see commonalities (from a superficial, protocol level), but I feel pretty strongly that trying to force them to fit the same mold is to awkwardly juxtapose two concepts that don't fit together too naturally.

**Comment by quartzjer** [comment]
Seems like a good time/place to talk levels of abstraction: it's all about services.  Services have always been about a single level of abstraction that embodies isolation (process+code), a namespace (http endpoint + fs dir), access (talk to other services, send/receive events), and a bit of scheduling.  While you can group them by different themes (connectors, collections, and even apps) they are still one clear level of abstraction, they are all peers in a person's data micro-ecosystem.

There's always been a deep intent to embrace a very open sense of innovation and experimentation in services, any dev should feel encouraged to clone one and extend it for a different purpose.  In the long run there will be competition and decay, the namespaces and which other services you choose to depend on are a dynamic thing, an organic evolution not a clean directory. Each service can strive to internally be a clean and powerful set of utilities around the value it's adding in either mapping in external data/utilities or building on existing local data, but there should be a growing directory of services available, something the registry will help enable and accelerate.

On search, I /do/ think we need to be experimental, and iteratively so, this is a step forward from clucene on that path and with r-trees available and the ability to do structured joins, there's a lot of untapped potential, which could happen inside of this service or inside of places or any other service by just copying the working patterns here (it's not that much code), I'm not idealistic about where that happens as long as it just happens :)  I'd rather see the functionality being created closest to where it's needed first, before trying to fit anything into a mold, and in this case we had done exactly that with search previously (was in two places) that happened to be the same mold, a simple text-based user facing search with optional type filtering and time sort.

Every service is going to have very different conceptual and concrete patterns around usage, storage, representations of data, that's something that makes them powerful as a participant in this mini ecology.

**Comment by amcjen** [comment]
Interesting dialog so far.  I think there's been a natural evolution of search.  It initially started as an app, with its own instance of Elasticsearch running.  We then kicked that out and moved to clucene, and created a search collection, as well as some common search endpoints in node/common.  I could see search naturally evolving itself closer to the collections that it indexes, meaning that each collection has a built-in search querying and indexing endpoint. 

I think this speaks more to what's happening in Temas's world with the Mongo replacement research, than to this pull request.  The search collection works now, if not completely semantically correct.  When a Mongo replacement is confirmed and brought in, it will speak volumes more in terms of what of search we can move closer to collections, and may influence search to be assimilated into collections altogether.  

I personally would like to see each collection have a /query and an /index endpoint that I can hit, rather than doing a /search/query?type=<some collection name>.   But 1000x more important is that I can search at all via the API, so as long as _some_  /query endpoint exists in the locker, we're doing pretty good.  My two bitcoins.

**Comment by smurthas** [comment]
+1 on erictj's bitcoins.

This pull is more about crossing off clucene and replacing it with something functional rather than any sort of reorganization. While the specific word "Collection" for search does feel strange, that is entirely tangential to whether this is a step forward for this component of the system.

I'm excited to see all this get in when we are able!

**Comment by othiym23** [comment]
I agree that first and foremost we need a search API that works. If CLucene isn't getting us there, then we absolutely need a replacement. I will point out here that this morning was the first time I'd heard the discussion framed in terms of CLucene being technically unacceptable rather than it being risky to depend on an EOL / dead project. That definitely recalibrates the priority.

My point of view resembles Eric's from the beginning of his final paragraph. Having an /index and /query endpoint exposed per Collection is the concrete version of the "cross-cutting concern" I was mentioning previously.

Furthermore, the reason I've spent so much time on distinguishing between service, collection, API, and related concepts is that it has been a source of ongoing confusion for me understanding why the system is laid out the way it is, and a good chunk of that confusion was rooted in not always having a solid grasp on which pieces of the architecture the team considers central and which are considered peripheral. Nomenclature is important.

Jer, I think you and I are thinking about abstraction in different ways, maybe. I'm largely preoccupied with the structure and type of the data, and you seem more interested in the flow of the data. I say this because I don't really see the kind of abstraction you were describing as particularly germane to this distinction. For me, the sticking point is that search is an activity (or verb) and Collections represent aggregates of documents (nouns). It seems to me that to say they're the same because they're both based on documents (some to be indexed, some to be browsed) is to rely on a very technical understanding of search that doesn't map well to how the two different things are used. I know there's overlap, but I think they are different kinds of data, and trying to make them fit together doesn't make sense.

**Comment by quartzjer** [comment]
I'm def thinking more of the flow, and I get the verb/noun thing, but don't want to constrain services in that way either.  This is mostly the search collection because that's what it was already, I just replaced the back-end, in a more true sense as I said earlier it's the "text collection" that has a query api :)

IMO also def see this evolving however it should best for the other collections, probably with them doing their own search, this collection is an excellent pattern to copy off of for that and for others like it.

**Pull request merged**
