### PR TITLE
SoundCloud synclet

### PR DESCRIPTION
**Pull request by smurthas**
Woo! More data! Pulls in (meta data for) tracks, followings, favorites, playlists, groups, and comments. 

For those interested, check out how I actually implemented the synclet code itself - only 16 lines of code to hit 6 diff endpoints (mostly because they are similar and simple, but still...).

I don't have any playlists, groups or comments in my account, so didn't write any tests for those parts, but they would be very straight forward to add.

### CODE REVIEW

**Comment by quartzjer** [comment]
This is GREAT! I have a reason to log into soundcloud more now!

**Comment by smurthas** [comment]
You can register an app at http://soundcloud.com/you/apps

**Comment by quartzjer** [comment]
+1, totally worked!

**Comment by smurthas** [comment]
Ok, master merged back in ("clashed" with gowalla merge -- lsyncmanager auth stuff). Merging...

**Pull request merged**
