### PR TITLE
Add Facebook's gender field to the Contacts dataMap

### PR DESCRIPTION
**Pull request by beaugunderson**
Simple addition to allow the Facebook connector to set a contact's gender.

### CODE REVIEW

**Comment by quartzjer** [comment]
The next bit to adding this is to have all the facebook contacts get updated to include this on existing lockers, a bit of an unknown we have to collectively figure out how to do :) cc @smurthas

**Comment by smurthas** [comment]
@quartzjer not sure what you mean? Facebook returns the gender field for everyone that specifies it (might even be required).

**Comment by quartzjer** [comment]
This is in the contacts collection though, it'll only have the gender field for contacts that are updated after this merge, versus there being some trigger after the code lands to update facebook contacts so they all have a gender.

**Comment by smurthas** [comment]
Yes. A migration would be needed, a global migration would work just fine, similar to how 0000000000000000000000000000000000000000000000000000000000000000000000000006.js works (request.get on postStartup)

@beaugunderson do you want to take a look at that migration and see if you can put together a similar one?

Perhaps we could actually trigger collection migrations with a package.json flag for the version, such that when it upgrades to the new version, it would just call /update.

**Comment by quartzjer** [comment]
Lol funny :)

Anyway, I've been experimenting with using npm's built-in script
framework to fire a postInstall process that would do a /update, where
I'm at is figuring out how to pass in the needed state (host:port
where locker is running, etc), or maybe just have it load lconfig or
something :/

On Mon, Jan 30, 2012 at 10:54 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by beaugunderson** [comment]
@smurthas something like this?

``` javascript

/*****************************
* Updates the contacts collection since we've added a new field to the dataMap
*/
var request = require("request");
var logger = require("logger");

module.exports.postStartup = function(config, callback) {
   request.get({uri:config.lockerBase + '/Me/contacts/update'}, function(err, resp, body) {
      if ((err || resp.statusCode !== 200) && body !== "already running") {
         if (resp.statusCode !== 200)
            logger.error("couldn't update contacts, response: " + body);

         if (err)
            logger.error(new Error(err).stack);

         return callback(false);
      }

      callback(true);
   });
};
```

**Comment by smurthas** [comment]
Yes, something like that! I'll have to test it tomorrow (on my phone now).

**Comment by quartzjer** [comment]
I just added support for this to master so it's not rolled out yet, but it allows us to tie a migration script to any version of any package in a useful way.  Add this to the version's package.json:

```
    "scripts": {
        "postinstall": "node update.js"
    }
```

and then update.js can be simply:

```
    require('request').get({uri:process.env.npm_config_locker_base+'/Me/contacts/update'});
```

**Comment by smurthas** [comment]
@quartzjer I don't think that the locker's HTTP endpoints will be available at that phase (as it will update before starting), so this would really still have to be a postStartup migration (or just queue something up somehow).

@beaugunderson if you want to just resubmit with that migration, I'll make sure it works and merge the pull.

**Comment by beaugunderson** [comment]
@smurthas I updated the commit range to include the migration file

**Pull request merged**
