### PR TITLE
Google Contacts Photos

### PR DESCRIPTION
**Pull request by smurthas**
Added contact photo download to gcontacts and a few migrations to make it happen. Also had to make a change to how lsyncmanager "reschedules" synclets if the exectuable flag is set to false.

### CODE REVIEW

**Comment by quartzjer** [comment]
This needs to be updated to master, and I thought the lsyncmanager fix was in master already (guess not), other than that it looks simple/good to me!

**Comment by smurthas** [comment]
All set!

**Comment by quartzjer** [comment]
tested it, it worked great, +1, merge it!

**Comment by temas** [comment]
If you can test with the latest master one more time, let's merge this bad boy, +1

**Comment by smurthas** [comment]
this is not ready to be merge, it revealed bugs in the contacts collection that i am fixing right now.

**Comment by smurthas** [comment]
This is all set to merge - could 1 person test once more and +1?

**Comment by quartzjer** [comment]
tested again, all good here, +1!

**Comment by smurthas** [comment]
Ok, this is ready to go - just need someone to get a fully updated master sync to gcontacts, then shutdown, move to gcontacts-photos branch and restart. You should see contacts collection update, search reindex and gcontacts run to pull in all your photos.

**Comment by temas** [comment]
+1 tested on my old Me dir and a fresh one.

**Pull request merged**
