### PR TITLE
Fresh paint

### PR DESCRIPTION
**Pull request by jsmecham**
Here's a pull request to keep my stuff in sync with master.  The TLP logo has not yet been updated for this design.  Includes cleanups to the design of UseUI and LinkaLatte.

### CODE REVIEW

**Comment by ctide** [comment]
Dropping down services breaks right now, so probably shouldn't merge this in.

http://imageshar.es/4e978a6c059ef06c320001fc

**Comment by jsmecham** [comment]
Ah, yea.  No worries, I'll fix that up and submit another pull request (probably won't be until tomorrow).

**Comment by smurthas** [comment]
Also, the top right shows the user menu through the "dashboard" config.json param. It ends up looking like this after it makes an AJAX request to the customHostedEndpoint -- http://bit.ly/px2jZT. Ends up overlapping with the new paint: http://bit.ly/rf5XWN.

It lives at about 167 of app.ejs in UseUI. Might be hard to test, but give it a shot -- talk to @temas if you need help getting that bit working!

Awesome!!!

**Comment by jsmecham** [comment]
The user menu and services drawer should no longer cause conflicts.  In addition, the contacts viewer has been update and a pull request generated for it as well (https://github.com/LockerProject/MergedContacts/pull/1).

**Comment by smurthas** [comment]
I'm going through this and will post back any tweaks needed

**Comment by smurthas** [comment]
Some items to be fixed, we can talk about them, but I wanted to get them down while I noticed them:

# High Priority

Z-index of gradient? -- http://bit.ly/pSt4pl
location of search dropdown (relative to input) -- http://bit.ly/pwiEsM
z-index of search (behind servies tray) -- http://bit.ly/ra02FO
counts gone from header
no title, etc in links (maybe just FB? maybe that a backend thing?) -- http://bit.ly/q27XK6
auth links need to pop out, keeps events coming into dashboard, (accountPopup fn from master code)
contacts infinite scroll broken
contacts search results count -- http://bit.ly/qwx1n1
links search results doesn't show count or "See all" link -- http://bit.ly/o7qNmi

# Low Priority

really long emails -- http://bit.ly/nFNevG
doesn't clear name in detailed view if there isn't a new one -- http://bit.ly/o6S5w8
white line below services tray visible on dark background viewers -- http://bit.ly/ogGXHa

**Comment by jsmecham** [comment]
Fixed the search dropdown. Other fixes forthcoming.

**Comment by jsmecham** [comment]
Fixed issues with the gradients in non-Safari browsers and titles in the People view when searching/etc.

**Comment by temas** [comment]
I'm working to get this merged.

**Comment by temas** [comment]
I squash merged this as 042963e4527cd44e28dafb4b071b2540ec5240a8 and it didn't seem to auto close this.  I'll try normal merge next time.

**Pull request closed without merging**
