### PR TITLE
Synclet Auth Cleanup

### PR DESCRIPTION
**Pull request by smurthas**
There are few goals of this work:
1. Make it easier to build a synclet -- de-obfuscate things as much as possible!!!
2. Move all the synclet-specfic auth code into the synclet dir itself such that:
   - Creating a new synclet doesn't require making changes to core files
   - Synclets become more package-like -- could be pulled in from a registry, etc.

There was lots of synclet-specific code in `Ops/webservice-synclets-auth.js` and `lsyncmanager.js` -- that all got moved to `auth.js` files in the synclet dirs, which get required into those two files. They can specify oauth2 settings, in which case they will use common code, or simply drop out and specify their own handler function (ala twitter, tumblr, and flickr, which each use their own cute variant of oauth 1). This felt like a good balance between abstraction and flexibility. From here on out, any service using oauth 2 should require no auth code and at all, and (in theory!) no new synclets should require changes core code -- woooo!

Since there were some naming clashes, I ended up removing old connector code for Flickr, GoogleContacts, and Twitter. That feels like a step forward to me (the code was dead and confusing), but if that is a concern, it is easy to change and bring back -- I don't want these improvements to get held up as a result of something like that.

### CODE REVIEW

**Comment by quartzjer** [comment]
OMFG, you beat me to it! I love you!!!

**Comment by smurthas** [comment]
Ok, merged back up (had the expected conflicts with the Gowalla and SoundCloud merges). Found a small bug in the SoundCloud synclet, so that's a bonus.

Good to be tested.

What we need is for at least two other people to test doing at least the following:
1. Existing Me dir:
   - Get a full Me dir from master (add all the services and let the synclets run)
   - move to this branch
   - restart locker
   - force every synclet to run again
   - Make sure nothing 401's or anything bad like that
2. New Me dir
   - Whack your old Me dir
   - Connect all services
   - Make sure everything auth ok: me.json files have valid auth keys, all synclets connect and pull down data
   - Ensure that your Google services have a refresh_token in the me.json's auth object!

thx!

**Comment by temas** [comment]
22 Dec 11:05:58 - info: Synclet locations starting for glatitude
22 Dec 11:05:59 - error: Google Latitude locations error:   Traceback (most recent call last):
  File "/Users/temas/singly/code/Locker/Common/python/synclet/client.py", line 66, in <module>

22 Dec 11:05:59 - error: Google Latitude locations error:       run(info)
  File "/Users/temas/singly/code/Locker/Common/python/synclet/client.py", line 20, in run
    sync = **import**((run['run'].rpartition('.'))[0])
  File "/Users/temas/singly/code/Locker/Connectors/GoogleLatitude/locations.py", line 1, in <module>
    import apiclient.discovery
ImportError: No module named apiclient.discovery

22 Dec 11:05:59 - error: Google Latitude locations  response fail: SyntaxError: Unexpected end of input of 
22 Dec 11:06:09 - info: Synclet recent starting for foursquare

**Comment by smurthas** [comment]
that last error was just a python libs deal.

**Comment by temas** [comment]
Just for documentation purposes, I gave this a +1 merge

**Pull request merged**
