### PR TITLE
Use a simple shell loop instead of forever

### PR DESCRIPTION
**Pull request by mdz**
This loses some of the fancier capabilities of forever, but should use fewer resources

### CODE REVIEW

**Comment by quartzjer** [comment]
I think this is a delete and re-add of lockerd.js? Can you instead do a git mv _lockerd.js lockerd.js so git doesn't reset the edit history of it?

**Comment by mdz** [comment]
I did:

git rm lockerd.js
git mv _lockerd.js lockerd.js

Maybe git lost the history when I stashed the changes or moved them over to a branch?

Anyway, there were no changes to either file.  I can just copy over the locker script if need be. The aim of the pull request was just to get feedback on the idea and implementation. What did you think?

**Comment by quartzjer** [comment]
Usually it shows a rename, no idea on the git voodoo, not a super big deal.

**Comment by mdz** [comment]
This would break many of the admin scripts if merged, because they rely on searching for process names and the like, e.g.:

  local locker_pid=$(lxc-ps aux --lxc | grep "${locker_name} [a-zA-Z0-9./ ?:+]\* node lockerd\.js" | awk '{print $3}')

**Comment by quartzjer** [comment]
Any newer thoughts on this pull req?

**Comment by mdz** [comment]
I still think this is the way to go.  However, I don't really want to spend the time reworking those shell functions to support this, when it already works with the newer stuff (slya). I figured it could wait until slya goes live.

**Comment by othiym23** [comment]
+1 -- forever.js was not being helpful in the most recent incident.

**Pull request merged**
