### PR TITLE
Stylized Facebook, Twitter, and Foursquare Connector Pages

### PR DESCRIPTION
**Pull request by tamersaadeh**
I created a node module that deals with generating the HTML page that is going to be sent to the user of Locker.
# Implemented common styles to the following connectors:

```
1. Twitter
2. Foursquare
3. Facebook
```
# Note:

All of the colors are the same in all clients this can be easily changed/modified by changing two elements of the array parameter of formatHTML(). First element is the color of the background of the header, and the second element is the color of the text in the header. For more details look at the docs of the function in `Common/node/html.js`.

### CODE REVIEW

**Comment by tamersaadeh** [comment]
Please don't pull this in until I fix/update my repository to the current dev, so the merge will be smoother.

**Comment by temas** [comment]
Could you reverify this against master?

**Comment by quartzjer** [comment]
I'm going to close this one since it's pretty old and against connectors that have changed a lot... wish we could have gotten it in though before things changed so much!

**Comment by tamersaadeh** [comment]
It's ok, I just couldn't fix it in time! :)

**Pull request closed without merging**
