### PR TITLE
Convert Google Latitude connector to a synclet

### PR DESCRIPTION
**Pull request by garyp**

### CODE REVIEW

**Comment by nym** [comment]
Thank you Gary!

We're going to do a code review ASAP.

**Comment by nym** [comment]
ctide took a stab at getting this working and wasn't successful. Can you make sure it's working with the latest? We believe the same API key for gcontacts can be used by glatitude, correct?

**Comment by nym** [comment]
Also if there are any special instructions to get up and running, please let us know.

**Comment by garyp** [comment]
i'll try to merge in HEAD and test again tonight.

as for api keys, the same one can be used for both glatitude and gcontacts. but you have to make sure that 1) your project (in the google api console) has latitude api access enabled, and 2) your api key has http://localhost:8042/auth/glatitude/auth listed as an allowed redirect uri.

**Comment by garyp** [comment]
it worked for me. can you let me know what exactly wasn't working (i.e. it wouldn't start, it wouldn't auth, it wouldn't sync)?

specifically, i did the following:
1. git clone git://github.com/LockerProject/Locker.git
2. merge in synclet-latitude branch from git://github.com/garyp/Locker.git
3. fix up merge conflicts (mostly because the "gplus" stuff was added in the same place as the "glatitude" stuff)
4. create a new Config/apikeys.json with a "glatitude" section
5. node lockerd.js
6. go to http://localhost:8042/, click on "get started", click on the "Google Latitude" icon, accept the oauth dialog from google
7. voila, it syncs :)

you should see location/glatitude events being fired in the lockerd log and http://localhost:8042/synclets/glatitude/getCurrent/location?limit=10 should return some records, as will mongodb: mongo localhost:27018/locker --eval 'db.asynclets_glatitude_location.count()'

**Comment by smurthas** [comment]
Hey Gary, sorry this is taking us so long to process! We'll take a look at this further and see what we can merge in soon!

**Comment by elsmorian** [comment]
I pulled this and got it working locally, though to install the synclet you have to use the old UI. Could I add a +1 to this pull? Having location data from Latitude would be very helpful for the stuff we are doing with Locker.

**Comment by quartzjer** [comment]
Finally got this done, the latitude stuff was easy but the git part was G-NARLY.

I have 5k latitude places, SO FREAKING COOL, THANK YOU!!!!

**Comment by garyp** [comment]
woo! finally merged in :) yeah, resolving the conflicts and submodule breakage when i merged my local repo was painful.

**Pull request merged**
